#version: "3"

services:
  mysql:
    image: mysql:8.0.12
    container_name: mysql
    restart: always
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cotacaodolar
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"